FROM node:18-alpine

# Adicionar volumes para hot reload
WORKDIR /app
ENV NODE_ENV=development

# Instalar nodemon globalmente
RUN npm install -g nodemon

# Modificar o comando para usar nodemon
CMD ["nodemon", "--legacy-watch", "index.js"] 