FROM node:18-alpine

WORKDIR /app

# Copiar apenas os arquivos necessários para instalar dependências
COPY package*.json ./

# Instalar dependências incluindo nodemon
RUN npm install && \
    npm install -g nodemon

# Configurar para desenvolvimento
ENV NODE_ENV=development

# Expor a porta do Next.js
EXPOSE 3000

# O código fonte será montado como volume
CMD ["npm", "run", "dev"] 