FROM maven:3.8.4-openjdk-17-slim

WORKDIR /app

# Copiar apenas o pom.xml primeiro
COPY pom.xml .

# Baixar dependências
RUN mvn dependency:go-offline

# O código fonte será montado como volume
CMD ["mvn", "spring-boot:run", "-Dspring-boot.run.jvmArguments='-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005'"] 